---
kind: pipeline
type: docker
name: Timelog

steps:
- name: Install node modules
  image: node:10.16.3
  commands:
  - npm install

- name: Build static web
  image: node:10.16.3
  commands:
  - npm run build

- name: Publish
  image: plugins/docker
  settings:
    repo: nightlord851108/timelog
    tags: ${DRONE_COMMIT_BRANCH}.${DRONE_COMMIT:7}
    username:
      from_secret: timelog_docker_user
    password:
      from_secret: timelog_docker_passwd

trigger:
  branch:
  - master
  event:
  - push
