---
kind: pipeline
type: docker

steps:
- name: Publish
  image: plugins/docker
  settings:
    repo: nightlord851108/timelog
    tags: ${DRONE_COMMIT_BRANCH}.${DRONE_COMMIT:7}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
