kind: secret
name: timelog_docker_user
data:
---
kind: secret
name: timelog_docker_passwd
data:
---
kind: secret
name: rancher_cluster_token
data:
---
kind: pipeline
type: docker
name: Timelog

steps:
- name: Install node modules
  image: node:10.16.3
  commands:
  - npm install

- name: Build static web
  image: node:10.16.3
  commands:
  - npm run build

- name: Publish
  image: plugins/docker
  settings:
    repo: nightlord851108/timelog
    tags: ${DRONE_COMMIT_BRANCH}.${DRONE_COMMIT_SHA:0:8}
    username:
      from_secret: timelog_docker_user
    password:
      from_secret: timelog_docker_passwd

# - name: Deploy
#   image: nightlord851108/kustomize
#   environment:
#     CLUSTER_TOKEN:
#       from_secret: rancher_cluster_token
#   commands:
#   - kustomize build kustomize/base | kubectl apply --server=ssl-rancher.csie.ntut.edu.tw  --token=${CLUSTER_TOKEN} --insecure-skip-tls-verify=true --namespace=ois -f -

trigger:
  branch:
  - master
  event:
  - push
