apiVersion: apps/v1
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"timelog-beta-loadbalancer","kind":"LoadBalancer","name":"http","protocol":"TCP"}]]'
