apiVersion: apps/v1
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"timelog-beta-loadbalancer","kind":"LoadBalancer","name":"http","protocol":"TCP"}]]'
    spec:
      containers:
        - name: timelog
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  key: MYSQL_HOST
                  name: db-secrets
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: db-secrets
            - name: MYSQL_PASSWD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWD
                  name: db-secrets
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DB
                  name: db-secrets
            - name: FB_ID
              valueFrom:
                secretKeyRef:
                  key: FB_ID
                  name: db-secrets
            - name: FB_SECRET
              valueFrom:
                secretKeyRef:
                  key: FB_SECRET
                  name: db-secrets
